# Generated by Django 3.2.9 on 2021-12-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citymodel',
            table='CITY_MODEL',
        ),
        migrations.AlterModelTable(
            name='countrymodel',
            table='COUNTRY_MODEL',
        ),
        migrations.AlterModelTable(
            name='temperaturemodel',
            table='TEMPERATURE_MODEL',
        ),
    ]
