# Generated by Django 3.2.9 on 2021-12-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20211208_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
